version: '3.9'

services:
  backend:
    build: .
    network_mode: "host"
    ports:
      - 8000:8000
    depends_on:
      - db
      - adminer
      - rabbitmq
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: mydatabaseuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

#  set up rabbitmq
  rabbitmq:
    image: rabbitmq:3-management
    container_name: "rabbitmq"
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: myrabbituser
      RABBITMQ_DEFAULT_PASS: myrabbitpassword
