# Generated by Django 5.0.2 on 2024-03-04 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_celery_beat", "0018_improve_crontab_helptext"),
        ("service", "0003_service_periodic_task"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="periodic_task",
        ),
        migrations.AddField(
            model_name="service",
            name="peiodic_task",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="django_celery_beat.periodictask",
            ),
        ),
    ]
