# Generated by Django 5.0.2 on 2024-03-04 00:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0004_remove_service_periodic_task_service_peiodic_task"),
    ]

    operations = [
        migrations.RenameField(
            model_name="service",
            old_name="peiodic_task",
            new_name="periodic_task",
        ),
    ]
