# Generated by Django 5.0.2 on 2024-02-26 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationlog',
            name='channel',
        ),
    ]
