# Generated by Django 5.0.2 on 2024-02-26 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_remove_notificationlog_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationchannel',
            name='type',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('bark', 'Bark')], default='bark', max_length=50),
        ),
    ]
