on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
name: Run tests
concurrency:
  group: check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: test with ${{ matrix.py }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: mydatabaseuser
          POSTGRES_PASSWORD: mypassword
          POSTGRES_DB: mydatabase
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    strategy:
      matrix:
        py:
          - "3.12.1"
          - "3.12.3"
        os:
          - ubuntu-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup python for test ${{ matrix.py }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.py }}
      - name: Install poetry
        run: |
          python -m pip install poetry
          poetry install
      - name: Set environment variables
        run: |
          echo "DATABASE_URL=postgresql://mydatabaseuser:mypassword@localhost:5432/mydatabase" >> $GITHUB_ENV
      - name: Run tests
        env:
          DATABASE_URL:localhost
          DATABASE_NAME:mydatabase
          DATABASE_PORT:5432
          DATABASE_USER:mydatabaseuser
          DATABASE_PASSWORD:mypassword
        run: poetry run pytest -vv
